name: Chain tests

# INFO: This workflow can't push to the repository
permissions: read-all

# INFO: Run workflow on changes to the sdks
on:
  push:
    paths:
      - 'src/multichain/**'
      - 'src/tests/multichain/**'

jobs:
  test:
    name: XM Chain tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run tests
        run: bun test:multichain
