name: Generate and Deploy TypeDoc

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy TypeDoc Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        run: yarn install
      - name: Add ts-ignore to superdilithium
        run: |
          echo '// @ts-nocheck' | cat - node_modules/superdilithium/index.d.ts > temp && mv temp node_modules/superdilithium/index.d.ts

      - name: Generate TypeDoc
        run: yarn typedoc

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Output deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
