name: Update README Version

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update README with version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          sed -i "s/release v[0-9]\+\.[0-9]\+\.[0-9]\+/release v${VERSION}/g" README.md
          
      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --quiet || (git add README.md && git commit -m "Update README version to v$(node -p "require('./package.json').version")")
          git push || true